/* Wspólny Portfel Offline 3.0 — moduł rozszerzeń */
const META_KEY='wpo30-meta';
let M=loadMeta();
let attachmentDraft=[];
function loadMeta(){try{return JSON.parse(localStorage.getItem(META_KEY))||defaults()}catch{return defaults()}}
function defaults(){return{opening:{},carry:true,events:[],installments:[],notes:{},assets:[]}}
function saveMeta(){localStorage.setItem(META_KEY,JSON.stringify(M))}
function prevMonth(k){const d=new Date(k+'-01T12:00');d.setMonth(d.getMonth()-1);return d.toISOString().slice(0,7)}
function monthDelta(k){const z=sum(S.items.filter(x=>x.date.startsWith(k)));return z.income-z.expense}
function carryInto(k,depth=0){if(!M.carry||depth>60)return 0;const p=prevMonth(k),has=Object.prototype.hasOwnProperty.call(M.opening,p),older=has?Number(M.opening[p]||0):carryInto(p,depth+1);return older+monthDelta(p)}
function startFor(k){return Number(M.opening[k]||0)+carryInto(k)}
function fmtDate(v){return v?new Date(v+'T12:00').toLocaleDateString('pl-PL'):'—'}
function daysLeft(v){return Math.ceil((new Date(v+'T23:59')-new Date())/86400000)}
function esc2(s){return esc(s)}

const oldPersist=persist;
persist=function(){oldPersist();saveMeta()};

const originalRender=render;
render=function(){
  originalRender();
  renderMonthBar();
};
function renderMonthBar(){
  const header=document.querySelector('main > header');
  if(!header)return;
  const oldButton=document.getElementById('monthBtn');
  if(oldButton)oldButton.classList.add('hidden');
  document.getElementById('monthStrip')?.remove();
  const selected=new Date(S.month+'-01T12:00');
  const year=selected.getFullYear();
  const names=['Sty','Lut','Mar','Kwi','Maj','Cze','Lip','Sie','Wrz','Paź','Lis','Gru'];
  const strip=document.createElement('section');
  strip.id='monthStrip';
  strip.className='month-strip';
  strip.innerHTML=`<button class="year-arrow" onclick="changeYear(-1)" aria-label="Poprzedni rok">‹</button><strong class="month-year">${year}</strong><div class="month-list">${names.map((name,i)=>{const key=year+'-'+String(i+1).padStart(2,'0');return `<button class="month-chip ${key===S.month?'active':''}" data-month="${key}" onclick="selectMonth('${key}')"><span>${name}</span></button>`}).join('')}</div><button class="year-arrow" onclick="changeYear(1)" aria-label="Następny rok">›</button>`;
  header.insertAdjacentElement('afterend',strip);
  requestAnimationFrame(()=>strip.querySelector('.month-chip.active')?.scrollIntoView({behavior:'smooth',block:'nearest',inline:'center'}));
}
function selectMonth(key){S.month=key;render();if(S.tab==='transactions')setTimeout(filter)}
function changeYear(delta){const d=new Date(S.month+'-01T12:00');d.setFullYear(d.getFullYear()+delta);selectMonth(d.toISOString().slice(0,7))}
const monthStyle=document.createElement('style');
monthStyle.textContent=`.month-strip{display:grid;grid-template-columns:auto auto minmax(0,1fr) auto;align-items:center;gap:12px;background:#fff;border:1px solid var(--l);border-radius:16px;padding:10px 12px;margin:-8px 0 24px;box-shadow:0 7px 22px #173f310d}.month-list{display:grid;grid-template-columns:repeat(12,minmax(52px,1fr));gap:6px;overflow-x:auto;scrollbar-width:thin;padding:2px}.month-chip,.year-arrow{border:0;background:#f4f7f5;border-radius:10px;min-height:42px;font-weight:700;color:#66716a}.month-chip:hover{background:#e5f1e9;color:var(--g)}.month-chip.active{background:var(--g);color:#fff;box-shadow:0 6px 14px #1e6f5038}.year-arrow{font-size:27px;width:42px;color:var(--g)}.month-year{font-size:17px;color:var(--d)}@media(max-width:900px){.month-strip{grid-template-columns:auto 1fr auto}.month-year{grid-column:1/-1;grid-row:1;text-align:center}.year-arrow:first-child{grid-column:1;grid-row:2}.month-list{grid-column:2;grid-row:2;display:flex}.month-chip{min-width:58px}.year-arrow:last-child{grid-column:3;grid-row:2}}`;
document.head.appendChild(monthStyle);

rows=function(a,buttons=false){return a.length?a.map(x=>`<div class="row"><div><b>${(x.attachments?.length||x.photo)?'📎 ':''}${esc2(x.merchant||x.description||x.category)}</b><small>${esc2(x.category)} · ${x.date} · ${x.person}${x.event?' · '+esc2(x.event):''}${x.warrantyEnd?' · gwarancja do '+fmtDate(x.warrantyEnd):''}</small></div><strong class="${x.type}">${x.type==='income'?'+':'−'}${cash(x.amount)}</strong>${(x.attachments?.length||x.photo)?`<button class="btn minor" onclick="showAttachments('${x.id}')">Załączniki (${x.attachments?.length||1})</button>`:''}${buttons?`<button class="btn minor" onclick="editTx('${x.id}')">Edytuj</button><button class="btn minor" onclick="removeTx('${x.id}')">Usuń</button>`:''}</div>`).join(''):'<p class="muted">Brak transakcji.</p>'};

home=function(){let a=current(),z=sum(a),start=startFor(S.month),bal=start+z.income-z.expense,c={};a.filter(x=>x.type==='expense').forEach(x=>c[x.category]=(c[x.category]||0)+x.amount);return `<section class="hero"><small>DOSTĘPNE W TYM MIESIĄCU</small><strong>${cash(bal)}</strong><span>Saldo początkowe i przeniesienie: ${cash(start)}</span></section><div class="cards"><div class="card"><small>SALDO NA START</small><br><b>${cash(start)}</b></div><div class="card"><small>PRZYCHODY</small><br><b class="income">${cash(z.income)}</b></div><div class="card"><small>WYDATKI</small><br><b class="expense">${cash(z.expense)}</b></div></div><section class="panel" style="margin-bottom:18px"><h2>Notatka do miesiąca</h2><textarea id="monthNote" rows="3" placeholder="Np. wakacje, naprawa samochodu, większa premia…" style="width:100%;margin-top:12px;padding:12px;border:1px solid var(--l);border-radius:10px">${esc2(M.notes[S.month]||'')}</textarea><button class="btn" style="margin-top:8px" onclick="saveMonthNote()">Zapisz notatkę</button></section><div class="grid"><section class="panel"><h2>Ostatnie transakcje</h2>${rows(a.slice().sort((x,y)=>y.date.localeCompare(x.date)).slice(0,6))}</section><section class="panel"><h2>Największe kategorie</h2>${Object.entries(c).sort((a,b)=>b[1]-a[1]).slice(0,7).map(x=>`<p><b>${esc2(x[0])}</b><span style="float:right">${cash(x[1])}</span></p>`).join('')||'<p class="muted">Brak wydatków.</p>'}</section></div><div class="actions"><button class="primary" onclick="txModal('expense')">+ Dodaj wydatek</button><button onclick="quick()">Szybki wydatek</button><button onclick="txModal('income')">+ Dodaj przychód</button></div>`};
function saveMonthNote(){M.notes[S.month]=document.getElementById('monthNote').value;saveMeta();toastMsg('Notatka miesiąca zapisana')}

const oldSummary=summary;
summary=function(){let base=oldSummary(),events={};current().filter(x=>x.event).forEach(x=>events[x.event]=(events[x.event]||0)+(x.type==='expense'?x.amount:0));let due=M.installments.filter(x=>!x.done),warranties=S.items.filter(x=>x.warrantyEnd&&daysLeft(x.warrantyEnd)>=0).sort((a,b)=>a.warrantyEnd.localeCompare(b.warrantyEnd)).slice(0,5);return base+`<div class="grid" style="margin-top:18px"><section class="panel"><h2>Wydarzenia i projekty</h2>${Object.entries(events).sort((a,b)=>b[1]-a[1]).map(x=>`<p><b>${esc2(x[0])}</b><span style="float:right">${cash(x[1])}</span></p>`).join('')||'<p class="muted">Brak wydatków przypisanych do wydarzeń.</p>'}</section><section class="panel"><h2>Najbliższe raty</h2>${due.slice(0,5).map(x=>`<p><b>${esc2(x.name)}</b><br><small>${cash(x.amount)} · ${fmtDate(x.nextDate)} · ${x.paid}/${x.count} zapłaconych</small></p>`).join('')||'<p class="muted">Brak aktywnych rat.</p>'}</section><section class="panel" style="grid-column:1/-1"><h2>Aktywne gwarancje</h2>${warranties.map(x=>`<p><b>${esc2(x.merchant||x.description)}</b><span style="float:right">do ${fmtDate(x.warrantyEnd)} (${daysLeft(x.warrantyEnd)} dni)</span></p>`).join('')||'<p class="muted">Brak zapisanych gwarancji.</p>'}</section></div>`};

const oldSettings=settings;
settings=function(){return oldSettings()+`<div class="settings" style="margin-top:18px"><section class="panel"><h2>Saldo i przenoszenie</h2><label>Saldo początkowe dla ${S.month}<input id="openingBalance" inputmode="decimal" value="${M.opening[S.month]??''}" placeholder="0,00"></label><label style="display:flex;gap:8px;margin-top:12px"><input type="checkbox" id="carryToggle" ${M.carry?'checked':''} style="width:auto"> Przenoś saldo automatycznie</label><button class="btn primary" style="margin-top:12px" onclick="saveBalanceSettings()">Zapisz</button></section><section class="panel"><h2>Wydarzenia i projekty</h2><form onsubmit="addEvent(event)"><input name="eventName" required placeholder="Np. Rodos 2026"><button class="btn primary">Dodaj</button></form>${M.events.map(x=>`<span class="tag">${esc2(x)} <button onclick="deleteEvent('${encodeURIComponent(x)}')">×</button></span>`).join('')}</section><section class="panel"><h2>Harmonogram rat</h2><button class="btn primary" onclick="installmentModal()">+ Dodaj ratę</button>${M.installments.map(x=>`<div class="row"><div><b>${esc2(x.name)}</b><small>${cash(x.amount)} · kolejna ${fmtDate(x.nextDate)} · ${x.paid}/${x.count}</small></div><button class="btn" onclick="payInstallment('${x.id}')">Zapłacona</button><button class="btn" onclick="deleteInstallment('${x.id}')">Usuń</button></div>`).join('')||'<p class="muted">Brak harmonogramu rat.</p>'}</section><section class="panel"><h2>Rejestr wartościowych zakupów</h2><button class="btn primary" onclick="assetModal()">+ Dodaj przedmiot</button>${M.assets.map(x=>`<div class="row"><div><b>${esc2(x.name)}</b><small>${cash(x.value)} · zakup ${fmtDate(x.date)}${x.warrantyEnd?' · gwarancja do '+fmtDate(x.warrantyEnd):''}</small></div><button class="btn" onclick="showAsset('${x.id}')">Szczegóły</button><button class="btn" onclick="deleteAsset('${x.id}')">Usuń</button></div>`).join('')||'<p class="muted">Rejestr jest pusty.</p>'}</section></div>`};
function saveBalanceSettings(){M.opening[S.month]=Number(document.getElementById('openingBalance').value.replace(',','.'))||0;M.carry=document.getElementById('carryToggle').checked;saveMeta();render();toastMsg('Saldo początkowe zapisane')}
function addEvent(e){e.preventDefault();let n=new FormData(e.target).get('eventName').trim();if(n&&!M.events.includes(n))M.events.push(n);saveMeta();render()}
function deleteEvent(n){n=decodeURIComponent(n);M.events=M.events.filter(x=>x!==n);saveMeta();render()}

txModal=function(type='expense',id='',preset={}){let x=S.items.find(i=>i.id===id)||{type,date:new Date().toISOString().slice(0,10),person:'Rafał',attachments:[],...preset};attachmentDraft=[...(x.attachments||[]),...(x.photo?[{id:uid(),name:'Paragon.jpg',type:'image/jpeg',data:x.photo}]:[])];openModal(id?'Edytuj transakcję':'Nowa transakcja',`<form class="form" id="txForm" onsubmit="saveTx(event,'${id}')"><div class="switch"><button type="button" id="ex" onclick="switchType('expense')" class="${x.type==='expense'?'active':''}">Wydatek</button><button type="button" id="incBtn" onclick="switchType('income')" class="${x.type==='income'?'active':''}">Przychód</button></div><input type="hidden" name="type" value="${x.type}"><label>Kwota<input required name="amount" inputmode="decimal" value="${x.amount||''}"></label><div class="cols"><label>Data<input required type="date" name="date" value="${x.date}"></label><label id="categoryLabel"></label></div><div id="expenseFields"></div><label>${x.type==='income'?'Kto otrzymał':'Kto zapłacił'}<select name="person"><option ${x.person==='Rafał'?'selected':''}>Rafał</option><option ${x.person==='Klaudia'?'selected':''}>Klaudia</option></select></label><button class="btn primary">Zapisz</button></form>`);switchType(x.type,x)};

switchType=function(t,x={}){let f=document.getElementById('txForm');f.elements.type.value=t;document.getElementById('ex').classList.toggle('active',t==='expense');document.getElementById('incBtn').classList.toggle('active',t==='income');document.getElementById('categoryLabel').innerHTML=t==='income'?`Rodzaj przychodu<select name="category">${S.incs.map(c=>`<option ${c===x.category?'selected':''}>${esc2(c)}</option>`).join('')}</select>`:`Kategoria<select name="category">${S.cats.map(c=>`<option ${c===x.category?'selected':''}>${esc2(c)}</option>`).join('')}</select>`;document.getElementById('expenseFields').innerHTML=t==='expense'?`<label>Sklep / miejsce<input name="merchant" value="${esc2(x.merchant||'')}" oninput="this.form.category.value=suggest(this.value)" placeholder="np. Lidl"></label><label>Opis<input name="description" value="${esc2(x.description||'')}"></label><label>Wydarzenie / projekt<input name="event" list="eventList" value="${esc2(x.event||'')}" placeholder="Opcjonalnie"></label><datalist id="eventList">${M.events.map(v=>`<option value="${esc2(v)}">`).join('')}</datalist><div class="cols"><label>Gwarancja do<input type="date" name="warrantyEnd" value="${x.warrantyEnd||''}"></label><label><span>Wartościowy zakup</span><select name="valuable"><option value="">Nie</option><option value="yes" ${x.assetId?'selected':''}>Dodaj do rejestru</option></select></label></div><section style="border:1px solid var(--l);border-radius:12px;padding:14px"><b>Paragon i inne załączniki</b><p class="muted">Dodaj paragon, fakturę, gwarancję lub potwierdzenie. Możesz wybrać kilka plików.</p><input type="file" id="attachmentInput" multiple accept="image/*,.pdf" onchange="addAttachments(event)"><div id="attachmentList"></div></section>`:'';renderAttachmentDraft()};
function renderAttachmentDraft(){let box=document.getElementById('attachmentList');if(!box)return;box.innerHTML=attachmentDraft.map(a=>`<div class="row"><div><b>${esc2(a.name)}</b><small>${a.type||'plik'}</small></div><button class="btn" type="button" onclick="previewAttachment('${a.id}')">Otwórz</button><button class="btn" type="button" onclick="removeAttachment('${a.id}')">Usuń</button></div>`).join('')||'<p class="muted">Brak załączników.</p>'}
async function addAttachments(e){for(const file of [...e.target.files]){try{const data=await fileToData(file);attachmentDraft.push({id:uid(),name:file.name,type:file.type,data})}catch{alert('Nie udało się dodać pliku '+file.name)}}renderAttachmentDraft();e.target.value=''}
function fileToData(file){return new Promise((resolve,reject)=>{const r=new FileReader();r.onerror=reject;r.onload=()=>{if(!file.type.startsWith('image/'))return resolve(r.result);const im=new Image();im.onerror=reject;im.onload=()=>{const max=1600,scale=Math.min(1,max/im.width),c=document.createElement('canvas');c.width=Math.round(im.width*scale);c.height=Math.round(im.height*scale);c.getContext('2d').drawImage(im,0,0,c.width,c.height);resolve(c.toDataURL('image/jpeg',.76))};im.src=r.result};r.readAsDataURL(file)})}
function removeAttachment(id){attachmentDraft=attachmentDraft.filter(a=>a.id!==id);renderAttachmentDraft()}
function previewAttachment(id){const a=attachmentDraft.find(x=>x.id===id);if(!a)return;openData(a)}
function openData(a){const w=window.open();if(!w)return alert('Przeglądarka zablokowała otwarcie załącznika.');if(a.type==='application/pdf')w.location.href=a.data;else w.document.write(`<title>${esc2(a.name)}</title><img src="${a.data}" style="max-width:100%;height:auto">`)}
function showAttachments(id){const x=S.items.find(i=>i.id===id),list=x?.attachments||[];if(!list.length&&x?.photo)list.push({id:'old',name:'Paragon.jpg',type:'image/jpeg',data:x.photo});openModal('Załączniki',list.map(a=>`<div class="row"><div><b>${esc2(a.name)}</b><small>${a.type}</small></div><button class="btn" onclick="openSavedAttachment('${id}','${a.id}')">Otwórz</button></div>`).join('')||'<p>Brak załączników.</p>')}
function openSavedAttachment(tx,id){const x=S.items.find(i=>i.id===tx),a=(x.attachments||[]).find(a=>a.id===id)||(x.photo?{name:'Paragon.jpg',type:'image/jpeg',data:x.photo}:null);if(a)openData(a)}

saveTx=function(e,id){e.preventDefault();let d=new FormData(e.target),amount=Number(String(d.get('amount')).replace(',','.')),old=S.items.find(x=>x.id===id),base={id:id||uid(),type:d.get('type'),amount,date:d.get('date'),category:d.get('category'),description:d.get('type')==='income'?d.get('category'):d.get('description'),merchant:d.get('type')==='income'?'':d.get('merchant'),person:d.get('person'),event:d.get('event')||'',warrantyEnd:d.get('warrantyEnd')||'',attachments:[...attachmentDraft],assetId:old?.assetId||''};if(old)S.items=S.items.map(x=>x.id===id?base:x);else S.items.unshift(base);if(d.get('valuable')==='yes'){let aid=base.assetId||uid(),asset={id:aid,name:base.description||base.merchant||'Wartościowy zakup',value:base.amount,date:base.date,warrantyEnd:base.warrantyEnd,transactionId:base.id,attachments:[...base.attachments]};let pos=M.assets.findIndex(a=>a.id===aid);if(pos>=0)M.assets[pos]=asset;else M.assets.unshift(asset);base.assetId=aid;S.items=S.items.map(x=>x.id===base.id?base:x)}log(old?`Rafał edytował ${base.merchant||base.category}: ${cash(old.amount)} → ${cash(base.amount)}`:`Rafał dodał ${base.merchant||base.category}: ${cash(base.amount)}`);closeModal();render()};

function installmentModal(){openModal('Dodaj harmonogram rat',`<form class="form" onsubmit="saveInstallment(event)"><label>Nazwa zakupu<input name="name" required placeholder="Np. telewizor"></label><div class="cols"><label>Kwota jednej raty<input name="amount" required inputmode="decimal"></label><label>Liczba rat<input name="count" required type="number" min="1"></label></div><div class="cols"><label>Zapłacone raty<input name="paid" type="number" min="0" value="0"></label><label>Termin następnej raty<input name="nextDate" required type="date"></label></div><button class="btn primary">Zapisz harmonogram</button></form>`)}
function saveInstallment(e){e.preventDefault();let d=new FormData(e.target);M.installments.unshift({id:uid(),name:d.get('name'),amount:Number(String(d.get('amount')).replace(',','.')),count:Number(d.get('count')),paid:Number(d.get('paid')),nextDate:d.get('nextDate'),done:false});saveMeta();closeModal();render()}
function payInstallment(id){let x=M.installments.find(x=>x.id===id);if(!x)return;x.paid=Math.min(x.count,x.paid+1);x.done=x.paid>=x.count;if(!x.done){let d=new Date(x.nextDate+'T12:00');d.setMonth(d.getMonth()+1);x.nextDate=d.toISOString().slice(0,10)}saveMeta();render()}
function deleteInstallment(id){M.installments=M.installments.filter(x=>x.id!==id);saveMeta();render()}

function assetModal(){openModal('Dodaj wartościowy przedmiot',`<form class="form" onsubmit="saveAsset(event)"><label>Nazwa<input name="name" required></label><div class="cols"><label>Wartość<input name="value" required inputmode="decimal"></label><label>Data zakupu<input name="date" required type="date"></label></div><label>Gwarancja do<input name="warrantyEnd" type="date"></label><label>Notatka<textarea name="note" rows="3"></textarea></label><button class="btn primary">Dodaj do rejestru</button></form>`)}
function saveAsset(e){e.preventDefault();let d=new FormData(e.target);M.assets.unshift({id:uid(),name:d.get('name'),value:Number(String(d.get('value')).replace(',','.')),date:d.get('date'),warrantyEnd:d.get('warrantyEnd'),note:d.get('note'),attachments:[]});saveMeta();closeModal();render()}
function showAsset(id){let a=M.assets.find(x=>x.id===id);if(a)openModal('Szczegóły przedmiotu',`<p><b>${esc2(a.name)}</b></p><p>Wartość: ${cash(a.value)}</p><p>Data zakupu: ${fmtDate(a.date)}</p><p>Gwarancja: ${fmtDate(a.warrantyEnd)}</p><p>${esc2(a.note||'')}</p>${a.transactionId?'<p><small>Połączony z wydatkiem.</small></p>':''}`)}
function deleteAsset(id){M.assets=M.assets.filter(x=>x.id!==id);saveMeta();render()}
function toastMsg(t){document.getElementById('toast').innerHTML=`<div class="toast">${esc2(t)}</div>`;setTimeout(()=>document.getElementById('toast').innerHTML='',2500)}

/* Rachunki i subskrypcje */
M.bills=M.bills||[];
const homeBeforeBills=home;
home=function(){
  const base=homeBeforeBills();
  const upcoming=M.bills.filter(x=>x.active!==false).sort((a,b)=>a.nextDate.localeCompare(b.nextDate)).slice(0,6);
  const section=`<section class="panel" style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><h2>Najbliższe rachunki i subskrypcje</h2><p class="muted">Telefon, internet, media, ubezpieczenia i serwisy</p></div><button class="btn primary" onclick="billModal()">+ Dodaj opłatę</button></div>${upcoming.map(b=>billRow(b,false)).join('')||'<p class="muted">Brak zaplanowanych opłat.</p>'}</section>`;
  return base+section;
};
const settingsBeforeBills=settings;
settings=function(){
  const base=settingsBeforeBills();
  return base+`<section class="panel" style="margin-top:18px"><div style="display:flex;justify-content:space-between;align-items:center;gap:12px"><div><h2>Rachunki i subskrypcje</h2><p class="muted">Cykliczne opłaty tworzą normalny wydatek po oznaczeniu jako zapłacone.</p></div><button class="btn primary" onclick="billModal()">+ Dodaj</button></div><div style="margin-top:12px">${M.bills.map(b=>billRow(b,true)).join('')||'<p class="muted">Nie dodano jeszcze żadnych opłat.</p>'}</div></section>`;
};
function billRow(b,manage){
  const left=daysLeft(b.nextDate),status=left<0?`zaległe ${Math.abs(left)} dni`:left===0?'dzisiaj':`za ${left} dni`;
  return `<div class="row"><div><b>${billIcon(b.kind)} ${esc2(b.name)}</b><small>${cash(b.amount)} · termin ${fmtDate(b.nextDate)} · ${frequencyName(b.frequency)} · ${esc2(b.person)} · ${status}</small></div><strong class="${left<0?'expense':''}">${cash(b.amount)}</strong><button class="btn primary" onclick="payBill('${b.id}')">Zapłacone</button>${manage?`<button class="btn minor" onclick="billModal('${b.id}')">Edytuj</button><button class="btn minor" onclick="deleteBill('${b.id}')">Usuń</button>`:''}</div>`;
}
function billIcon(k){return({Telefon:'📱',Internet:'🌐',Prąd:'⚡',Woda:'💧',Gaz:'🔥',Telewizja:'📺',Subskrypcja:'▶️',Ubezpieczenie:'🛡️',Inne:'🧾'})[k]||'🧾'}
function frequencyName(f){return({monthly:'co miesiąc',quarterly:'co 3 miesiące',yearly:'co rok'})[f]||'co miesiąc'}
function billModal(id=''){
  const b=M.bills.find(x=>x.id===id)||{name:'',kind:'Telefon',amount:'',category:'Rachunki i media',person:'Rafał',frequency:'monthly',nextDate:new Date().toISOString().slice(0,10),active:true};
  openModal(id?'Edytuj opłatę':'Nowy rachunek lub subskrypcja',`<form class="form" onsubmit="saveBill(event,'${id}')"><label>Nazwa opłaty<input name="name" required value="${esc2(b.name)}" placeholder="Np. Orange Rafał, Internet, Netflix"></label><div class="cols"><label>Rodzaj<select name="kind">${['Telefon','Internet','Prąd','Woda','Gaz','Telewizja','Subskrypcja','Ubezpieczenie','Inne'].map(x=>`<option ${x===b.kind?'selected':''}>${x}</option>`).join('')}</select></label><label>Kwota<input name="amount" required inputmode="decimal" value="${b.amount}"></label></div><div class="cols"><label>Powtarzanie<select name="frequency"><option value="monthly" ${b.frequency==='monthly'?'selected':''}>Co miesiąc</option><option value="quarterly" ${b.frequency==='quarterly'?'selected':''}>Co 3 miesiące</option><option value="yearly" ${b.frequency==='yearly'?'selected':''}>Co rok</option></select></label><label>Najbliższy termin<input name="nextDate" required type="date" value="${b.nextDate}"></label></div><div class="cols"><label>Kategoria<select name="category">${S.cats.map(x=>`<option ${x===b.category?'selected':''}>${esc2(x)}</option>`).join('')}</select></label><label>Kto płaci<select name="person"><option ${b.person==='Rafał'?'selected':''}>Rafał</option><option ${b.person==='Klaudia'?'selected':''}>Klaudia</option></select></label></div><label style="display:flex;gap:8px"><input type="checkbox" name="active" ${b.active!==false?'checked':''} style="width:auto"> Opłata aktywna</label><button class="btn primary">Zapisz opłatę</button></form>`);
}
function saveBill(e,id){
  e.preventDefault();const d=new FormData(e.target),bill={id:id||uid(),name:d.get('name'),kind:d.get('kind'),amount:Number(String(d.get('amount')).replace(',','.')),category:d.get('category'),person:d.get('person'),frequency:d.get('frequency'),nextDate:d.get('nextDate'),active:d.get('active')==='on'};
  if(id)M.bills=M.bills.map(x=>x.id===id?bill:x);else M.bills.unshift(bill);
  saveMeta();closeModal();render();toastMsg('Opłata zapisana');
}
function payBill(id){
  const b=M.bills.find(x=>x.id===id);if(!b)return;
  const exists=S.items.some(x=>x.billId===id&&x.date===b.nextDate);
  if(!exists)S.items.unshift({id:uid(),type:'expense',amount:b.amount,date:b.nextDate,category:b.category,description:b.name,merchant:b.kind,person:b.person,billId:b.id,attachments:[]});
  const date=new Date(b.nextDate+'T12:00');date.setMonth(date.getMonth()+(b.frequency==='quarterly'?3:b.frequency==='yearly'?12:1));b.lastPaid=b.nextDate;b.nextDate=date.toISOString().slice(0,10);
  log(`${b.person} opłacił(a): ${b.name}, ${cash(b.amount)}`);saveMeta();render();toastMsg('Opłata dodana do wydatków, kolejny termin przesunięty');
}
function deleteBill(id){if(!confirm('Usunąć tę cykliczną opłatę?'))return;M.bills=M.bills.filter(x=>x.id!==id);saveMeta();render()}

render();

/* v5 — pulpit infograficzny 50/30/20 */
function categoryIcon(n=''){n=n.toLowerCase();if(/spoży|zakup/.test(n))return'🛒';if(/mieście/.test(n))return'🍔';if(/rach|media/.test(n))return'🏠';if(/dom/.test(n))return'🪴';if(/dziecko/.test(n))return'🧸';if(/auto|paliwo/.test(n))return'🚗';if(/zdrow|aptek/.test(n))return'💊';if(/ubran/.test(n))return'👕';if(/kosmet/.test(n))return'🛍️';if(/rozryw/.test(n))return'🎬';if(/wyjaz|wakac/.test(n))return'🏖️';if(/ubez/.test(n))return'🛡️';if(/rat|kred/.test(n))return'🏦';return'🧾'}
function groupFor(n=''){n=n.toLowerCase();if(/jedzenie na mieście|ubrania|kosmetyki|rozrywka|wyjazdy|wakacje|prezenty/.test(n))return'wants';return'needs'}
function catLines(a){return a.length?a.slice(0,7).map(([n,v])=>`<div class="category-line"><span class="emoji">${categoryIcon(n)}</span><b>${esc2(n)}</b><strong>${cash(v)}</strong></div>`).join(''):'<p class="muted">Dodaj pierwsze wydatki, a tutaj pojawi się czytelny podział.</p>'}
function percent(v,t){return t>0?Math.round(v/t*100):0}
home=function(){
 const a=current(),z=sum(a),start=startFor(S.month),available=start+z.income,expense=a.filter(x=>x.type==='expense'),g={needs:{},wants:{}};
 expense.forEach(x=>{const k=groupFor(x.category);g[k][x.category]=(g[k][x.category]||0)+x.amount});
 const entries=k=>Object.entries(g[k]).sort((x,y)=>y[1]-x[1]),total=k=>Object.values(g[k]).reduce((s,v)=>s+v,0),needs=total('needs'),wants=total('wants'),saved=Math.max(0,available-needs-wants);
 const ra=a.filter(x=>x.type==='income'&&x.person==='Rafał').reduce((s,x)=>s+x.amount,0),kl=a.filter(x=>x.type==='income'&&x.person==='Klaudia').reduce((s,x)=>s+x.amount,0),top=expense.slice().sort((x,y)=>y.amount-x.amount)[0];
 return `<section class="panel family-intro"><div><span class="eyebrow">WSPÓLNY PORTFEL · ${new Date(S.month+'-01T12:00').toLocaleDateString('pl-PL',{month:'long'}).toUpperCase()}</span><h2>Miesięczny budżet Rafała i Klaudii</h2><span class="family-badge">👨‍👩‍👦 RODZINA 2+1</span></div><div class="home-art"><svg viewBox="0 0 260 150" fill="none"><path d="M55 112V59l68-43 68 43v53" stroke="#315c48" stroke-width="6"/><path d="M45 60l78-49 78 49M101 112V76h43v36M159 72h20v21h-20z" stroke="#b96f62" stroke-width="5"/><circle cx="35" cy="91" r="17" stroke="#315c48" stroke-width="5"/><path d="M35 108v25M19 133h217" stroke="#315c48" stroke-width="5"/><circle cx="216" cy="108" r="13" stroke="#315c48" stroke-width="5"/></svg></div></section>
 <div class="income-strip"><div class="income-box"><small>👨 RAFAŁ · PRZYCHODY</small><b>${cash(ra)}</b></div><div class="income-box"><small>👩 KLAUDIA · PRZYCHODY</small><b>${cash(kl)}</b></div><div class="income-box total"><small>RAZEM DOSTĘPNE</small><b>${cash(available)}</b></div></div>
 <div class="budget-grid"><section class="panel budget-card needs"><div class="budget-title"><h2>✓ Potrzeby</h2><span class="percent-pill">${percent(needs,available)}% / cel 50%</span></div>${catLines(entries('needs'))}<div class="progress"><i style="width:${Math.min(100,percent(needs,available)*2)}%"></i></div><div class="budget-total"><span>Razem</span><span>${cash(needs)}</span></div></section>
 <section class="panel budget-card wants"><div class="budget-title"><h2>♥ Zachcianki</h2><span class="percent-pill">${percent(wants,available)}% / cel 30%</span></div>${catLines(entries('wants'))}<div class="progress"><i style="width:${Math.min(100,percent(wants,available)/.3)}%"></i></div><div class="budget-total"><span>Razem</span><span>${cash(wants)}</span></div></section>
 <section class="panel budget-card savings"><div class="budget-title"><h2>↗ Oszczędności</h2><span class="percent-pill">${percent(saved,available)}% / cel 20%</span></div><p class="muted">Kwota pozostająca po wszystkich wydatkach.</p><div class="progress"><i style="width:${Math.min(100,percent(saved,available)*5)}%"></i></div><div class="budget-total"><span>Pozostało</span><span>${cash(saved)}</span></div></section>
 <section class="panel"><h2>Podział budżetu</h2><div class="split-summary"><div class="split-row-v5"><i class="dot"></i><span>Potrzeby</span><b>${cash(needs)} / ${percent(needs,available)}%</b></div><div class="split-row-v5"><i class="dot wants"></i><span>Zachcianki</span><b>${cash(wants)} / ${percent(wants,available)}%</b></div><div class="split-row-v5"><i class="dot savings"></i><span>Oszczędności</span><b>${cash(saved)} / ${percent(saved,available)}%</b></div><div class="split-row-v5"><i class="dot" style="background:#26352e"></i><strong>Łącznie</strong><strong>${cash(available)} / 100%</strong></div></div></section>
 <section class="panel insight"><span class="eyebrow">WARTO WIEDZIEĆ</span><p>${top?`Największy wydatek to <b>${esc2(top.merchant||top.description||top.category)}</b>: ${cash(top.amount)}.`:'Dodaj przychody i wydatki — tutaj pojawią się automatyczne wskazówki.'}</p><p class="muted">Notatka miesiąca: ${esc2(M.notes[S.month]||'brak')}</p></section><section class="panel insight-note"><div class="pin"></div><strong>${saved>0?`Po wydatkach zostaje ${cash(saved)}.`:`Budżet nie ma jeszcze wolnych środków.`}<br>${available>0&&percent(saved,available)>=20?'Cel oszczędności 20% jest osiągnięty.':'Każda odłożona kwota może zacząć pracować.'}</strong></section></div>
 ${M.bills?.length?`<section class="panel" style="margin-top:18px"><div class="budget-title"><div><h2>📅 Najbliższe rachunki i subskrypcje</h2><p class="muted">Telefon, internet, media, ubezpieczenia i serwisy</p></div><button class="btn primary" onclick="billModal()">+ Dodaj opłatę</button></div>${M.bills.filter(x=>x.active!==false).sort((x,y)=>x.nextDate.localeCompare(y.nextDate)).slice(0,5).map(b=>billRow(b,false)).join('')}</section>`:''}
 <div class="actions"><button class="primary" onclick="txModal('expense')">+ Dodaj wydatek</button><button onclick="quick()">Szybki wydatek</button><button onclick="txModal('income')">+ Dodaj przychód</button></div>`;
};
render();
